;;; password-generator-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from password-generator.el

(autoload 'password-generator-random "password-generator" "\
Random number limited by MAX.  Feel free to rewrite this random.  Just don't make it too slow.

(fn MAX)")
(autoload 'password-generator-random-list-element "password-generator" "\
Return random element from LIST.

(fn LIST)")
(autoload 'password-generator-get-random-string-char "password-generator" "\
You pass here STRING.  You get random character from it.

(fn STRING)")
(autoload 'password-generator-generate-internal "password-generator" "\
Generate the password with given vocabulary and length.  SYMBOLS-FOR-PASS is a string contining lphabet used for password generation.  PASS-LENGTH limits the password length.

(fn SYMBOLS-FOR-PASS PASS-LENGTH)")
(autoload 'password-generator-simple "password-generator" "\
Minimal viable password for most of web systems.  It is not secure but allow to register.  PRE-LEN is prefix arg that defines password lenght.  RETURN specifies if password should be returned or inserted.

(fn &optional PRE-LEN RETURN)" t)
(autoload 'password-generator-strong "password-generator" "\
The best password you can get.  Some symbols does not included to make you free from problems which occurs when your shell try interpolate $, \\ and others.  PRE-LEN is prefix arg that defines password lenght.  RETURN specifies if password should be returned or inserted.

(fn &optional PRE-LEN RETURN)" t)
(autoload 'password-generator-paranoid "password-generator" "\
Good thing to use if you really care about bruteforce.  Not all applications handle special characters presented in such password properly.  Be ready to escape special characters if you will pass such password via ssh command or so.  PRE-LEN is prefix arg that defines password lenght.  RETURN specifies if password should be returned or inserted.

(fn &optional PRE-LEN RETURN)" t)
(autoload 'password-generator-numeric "password-generator" "\
Yeah, there are sill reasons to use numeric passwords like credit card PIN-code.  PRE-LEN is prefix arg that defines password lenght.  RETURN specifies if password should be returned or inserted.

(fn &optional PRE-LEN RETURN)" t)
(autoload 'password-generator-phonetic "password-generator" "\
It will be easy to remeber, because of fonetic, but not so secure...  PRE-LEN is prefix arg that defines password lenght.  RETURN specifies if password should be returned or inserted.

(fn &optional PRE-LEN RETURN)" t)
(autoload 'password-generator-custom "password-generator" "\
Password generated with your own alphabet.  PRE-LEN is prefix arg that defines password lenght.  RETURN specifies if password should be returned or inserted.

(fn &optional PRE-LEN RETURN)" t)
(register-definition-prefixes "password-generator" '("password-generator-"))

;;; End of scraped data

(provide 'password-generator-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; password-generator-autoloads.el ends here
