;;; link-hint-aw-select-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from link-hint-aw-select.el

(autoload 'link-hint-aw-select "link-hint-aw-select" "\
Use avy to open a link in a window selected with ace-window." t)
(register-definition-prefixes "link-hint-aw-select" '("button" "define-link-hint-aw-select" "dired-filename" "link-hint--aw-select-" "org-link"))

;;; End of scraped data

(provide 'link-hint-aw-select-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; link-hint-aw-select-autoloads.el ends here
