;;; request-deferred-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from request-deferred.el

(register-definition-prefixes "request-deferred" '("request-deferred"))

;;; End of scraped data

(provide 'request-deferred-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; request-deferred-autoloads.el ends here
