;;; melpazoid-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from melpazoid.el

(autoload 'melpazoid "melpazoid" "\
Check current buffer, or FILENAME's buffer if given.

(fn &optional FILENAME)" t)
(register-definition-prefixes "melpazoid" '("melpazoid-"))

;;; End of scraped data

(provide 'melpazoid-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; melpazoid-autoloads.el ends here
