;;; bookmark-view-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from bookmark-view.el

(autoload 'bookmark-view-names "bookmark-view" "\
Return a list of names of all view bookmarks.")
(autoload 'bookmark-view-handler-fallback "bookmark-view" "\
Handle buffer bookmark BM, used for buffers without file.

(fn BM)")
(autoload 'bookmark-view-handler "bookmark-view" "\
Handle view bookmark BM.

(fn BM)")
(autoload 'bookmark-view "bookmark-view" "\
If view bookmark NAME exists, open it, otherwise save current view.

(fn NAME)" t)
(autoload 'bookmark-view-save "bookmark-view" "\
Save current view under the given NAME.
If NO-OVERWRITE is non-nil push to the bookmark list
without overwriting an already existing bookmark.

(fn NAME &optional NO-OVERWRITE)" t)
(autoload 'bookmark-view-open "bookmark-view" "\
Open view bookmark BM.

(fn BM)" t)
(autoload 'bookmark-view-delete "bookmark-view" "\
Delete view bookmark NAME.

(fn NAME)" t)
(autoload 'bookmark-view-rename "bookmark-view" "\
Rename bookmark from OLD name to NEW name.

(fn OLD &optional NEW)" t)
(autoload 'bookmark-view-push "bookmark-view" "\
Save current view as a bookmark with a default name." t)
(autoload 'bookmark-view-pop "bookmark-view" "\
Pop a bookmark view with a name matching `bookmark-view-name-regexp'." t)
(register-definition-prefixes "bookmark-view" '("bookmark-view-"))

;;; End of scraped data

(provide 'bookmark-view-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bookmark-view-autoloads.el ends here
