;;; emacs-calfw-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from calfw.el

(register-definition-prefixes "calfw" '("cfw:"))


;;; Generated autoloads from calfw-cal.el

(register-definition-prefixes "calfw-cal" '("cfw:"))


;;; Generated autoloads from calfw-howm.el

(register-definition-prefixes "calfw-howm" '("cfw:"))


;;; Generated autoloads from calfw-ical.el

(register-definition-prefixes "calfw-ical" '("cfw:"))


;;; Generated autoloads from calfw-org.el

(register-definition-prefixes "calfw-org" '("cfw:o"))

;;; End of scraped data

(provide 'emacs-calfw-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; emacs-calfw-autoloads.el ends here
