;;; dwim-shell-command-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from dwim-shell-command.el

(register-definition-prefixes "dwim-shell-command" '("dwim-shell-command"))


;;; Generated autoloads from dwim-shell-commands.el

(register-definition-prefixes "dwim-shell-commands" '("dwim-shell-commands-"))

;;; End of scraped data

(provide 'dwim-shell-command-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dwim-shell-command-autoloads.el ends here
