;;; wgrep-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from wgrep.el

(autoload 'wgrep-setup "wgrep" "\
Setup wgrep preparation.")
(add-hook 'grep-setup-hook 'wgrep-setup)
(register-definition-prefixes "wgrep" '("wgrep-"))

;;; End of scraped data

(provide 'wgrep-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wgrep-autoloads.el ends here
