;;; calfw-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from calfw.el

(register-definition-prefixes "calfw" '("calfw-" "displayed-"))


;;; Generated autoloads from calfw-cal.el

(register-definition-prefixes "calfw-cal" '("calfw-cal-"))


;;; Generated autoloads from calfw-howm.el

(register-definition-prefixes "calfw-howm" '("calfw-howm-"))


;;; Generated autoloads from calfw-ical.el

(register-definition-prefixes "calfw-ical" '("calfw-ical-"))


;;; Generated autoloads from calfw-org.el

(register-definition-prefixes "calfw-org" '("calfw-o"))

;;; End of scraped data

(provide 'calfw-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; calfw-autoloads.el ends here
