;;; accent-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from accent.el

(autoload 'accent-menu "accent" "\
Display a popup menu with available accents if current character is matching." t)
(register-definition-prefixes "accent" '("accent-"))

;;; End of scraped data

(provide 'accent-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; accent-autoloads.el ends here
