;;; link-hint-preview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from link-hint-preview.el

(autoload 'link-hint-preview "link-hint-preview" "\
Use avy to view link contents in a pop-up frame.
Set frame parameters in 'link-hint-preview-frame-parameters'." t)
(register-definition-prefixes "link-hint-preview" '("link-hint-preview-"))

;;; End of scraped data

(provide 'link-hint-preview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; link-hint-preview-autoloads.el ends here
