;;; compat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from compat.el

(register-definition-prefixes "compat" '("compat-"))


;;; Generated autoloads from compat-macs.el

(register-definition-prefixes "compat-macs" '("compat-"))

;;; End of scraped data

(provide 'compat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; compat-autoloads.el ends here
