;;; pdf-drop-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from pdf-drop-mode.el

(register-definition-prefixes "pdf-drop-mode" '("pdf-drop-"))

;;; End of scraped data

(provide 'pdf-drop-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pdf-drop-mode-autoloads.el ends here
